# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_task.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddTaskWindow(object):
    def setupUi(self, AddTaskWindow):
        AddTaskWindow.setObjectName("AddTaskWindow")
        AddTaskWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(AddTaskWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(190, 30, 431, 531))
        self.frame.setMinimumSize(QtCore.QSize(431, 531))
        self.frame.setStyleSheet("#frame{\n"
"    border-radius:15px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(130, 80, 141, 41))
        self.label.setMinimumSize(QtCore.QSize(111, 41))
        self.label.setStyleSheet("font: 75 20pt \"微软雅黑\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setGeometry(QtCore.QRect(50, 120, 311, 291))
        self.widget_2.setStyleSheet("QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_F_check_2 = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_F_check_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_F_check_2.setSizePolicy(sizePolicy)
        self.lineEdit_F_check_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_check_2.setText("")
        self.lineEdit_F_check_2.setObjectName("lineEdit_F_check_2")
        self.verticalLayout.addWidget(self.lineEdit_F_check_2)
        self.lineEdit_F_check = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_F_check.sizePolicy().hasHeightForWidth())
        self.lineEdit_F_check.setSizePolicy(sizePolicy)
        self.lineEdit_F_check.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_check.setObjectName("lineEdit_F_check")
        self.verticalLayout.addWidget(self.lineEdit_F_check)
        self.lineEdit_F_password1 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_F_password1.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_password1.setObjectName("lineEdit_F_password1")
        self.verticalLayout.addWidget(self.lineEdit_F_password1)
        self.comboBox = QtWidgets.QComboBox(self.widget_2)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.frame1 = QtWidgets.QFrame(self.frame)
        self.frame1.setGeometry(QtCore.QRect(310, 0, 111, 32))
        self.frame1.setStyleSheet("QPushButton:hover{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.frame1.setObjectName("frame1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame1)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_3.setStyleSheet("border:none;")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resource/icons/24gl-minimization.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame1)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_4.setStyleSheet("border:none;")
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resource/icons/Close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.frame2 = QtWidgets.QFrame(self.frame)
        self.frame2.setGeometry(QtCore.QRect(100, 411, 211, 41))
        self.frame2.setStyleSheet("QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.frame2.setObjectName("frame2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_A_everyday = QtWidgets.QPushButton(self.frame2)
        self.pushButton_A_everyday.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_A_everyday.setObjectName("pushButton_A_everyday")
        self.horizontalLayout.addWidget(self.pushButton_A_everyday)
        self.pushButton_A_ordinary = QtWidgets.QPushButton(self.frame2)
        self.pushButton_A_ordinary.setEnabled(True)
        self.pushButton_A_ordinary.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_A_ordinary.setObjectName("pushButton_A_ordinary")
        self.horizontalLayout.addWidget(self.pushButton_A_ordinary)
        AddTaskWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AddTaskWindow)
        self.statusbar.setObjectName("statusbar")
        AddTaskWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AddTaskWindow)
        self.pushButton_3.clicked.connect(AddTaskWindow.showMinimized) # type: ignore
        self.pushButton_4.clicked.connect(AddTaskWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddTaskWindow)

    def retranslateUi(self, AddTaskWindow):
        _translate = QtCore.QCoreApplication.translate
        AddTaskWindow.setWindowTitle(_translate("AddTaskWindow", "MainWindow"))
        self.label.setText(_translate("AddTaskWindow", "新建任务"))
        self.lineEdit_F_check_2.setPlaceholderText(_translate("AddTaskWindow", "任务名称："))
        self.lineEdit_F_check.setPlaceholderText(_translate("AddTaskWindow", "任务内容："))
        self.lineEdit_F_password1.setPlaceholderText(_translate("AddTaskWindow", "截止时间："))
        self.comboBox.setItemText(0, _translate("AddTaskWindow", "请选择任务类型"))
        self.comboBox.setItemText(1, _translate("AddTaskWindow", "学习"))
        self.comboBox.setItemText(2, _translate("AddTaskWindow", "运动"))
        self.comboBox.setItemText(3, _translate("AddTaskWindow", "生活"))
        self.pushButton_A_everyday.setText(_translate("AddTaskWindow", "每日任务"))
        self.pushButton_A_ordinary.setText(_translate("AddTaskWindow", "普通任务"))
import resource_rc
