# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'find_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FindWindow(object):
    def setupUi(self, FindWindow):
        FindWindow.setObjectName("FindWindow")
        FindWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(FindWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(250, 130, 401, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(361, 381))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(131, 31))
        self.label.setStyleSheet("font: 20pt \"Agency FB\";")
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(60, 70, 231, 291))
        self.frame_2.setStyleSheet("QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_F_check_2 = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_F_check_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_F_check_2.setSizePolicy(sizePolicy)
        self.lineEdit_F_check_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_check_2.setText("")
        self.lineEdit_F_check_2.setObjectName("lineEdit_F_check_2")
        self.verticalLayout.addWidget(self.lineEdit_F_check_2)
        self.lineEdit_F_check = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_F_check.sizePolicy().hasHeightForWidth())
        self.lineEdit_F_check.setSizePolicy(sizePolicy)
        self.lineEdit_F_check.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_check.setObjectName("lineEdit_F_check")
        self.verticalLayout.addWidget(self.lineEdit_F_check)
        self.lineEdit_F_password1 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_F_password1.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_password1.setObjectName("lineEdit_F_password1")
        self.verticalLayout.addWidget(self.lineEdit_F_password1)
        self.lineEdit_F_password2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_F_password2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_password2.setObjectName("lineEdit_F_password2")
        self.verticalLayout.addWidget(self.lineEdit_F_password2)
        self.pushButton_F_ensure = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_F_ensure.setObjectName("pushButton_F_ensure")
        self.verticalLayout.addWidget(self.pushButton_F_ensure, 0, QtCore.Qt.AlignHCenter)
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setGeometry(QtCore.QRect(300, 0, 91, 41))
        self.frame_10.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_10)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/24gl-minimization.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/Close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_F_send = QtWidgets.QPushButton(self.frame)
        self.pushButton_F_send.setGeometry(QtCore.QRect(290, 90, 81, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_F_send.sizePolicy().hasHeightForWidth())
        self.pushButton_F_send.setSizePolicy(sizePolicy)
        self.pushButton_F_send.setMinimumSize(QtCore.QSize(81, 29))
        self.pushButton_F_send.setStyleSheet("QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_F_send.setObjectName("pushButton_F_send")
        FindWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FindWindow)
        self.statusbar.setObjectName("statusbar")
        FindWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FindWindow)
        self.pushButton.clicked.connect(FindWindow.showMinimized) # type: ignore
        self.pushButton_2.clicked.connect(FindWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FindWindow)

    def retranslateUi(self, FindWindow):
        _translate = QtCore.QCoreApplication.translate
        FindWindow.setWindowTitle(_translate("FindWindow", "MainWindow"))
        self.label.setText(_translate("FindWindow", "找回密码"))
        self.lineEdit_F_check_2.setPlaceholderText(_translate("FindWindow", "邮箱："))
        self.lineEdit_F_check.setPlaceholderText(_translate("FindWindow", "验证码："))
        self.lineEdit_F_password1.setPlaceholderText(_translate("FindWindow", "密码："))
        self.lineEdit_F_password2.setPlaceholderText(_translate("FindWindow", "确认密码："))
        self.pushButton_F_ensure.setText(_translate("FindWindow", "确认"))
        self.pushButton_F_send.setText(_translate("FindWindow", "发送验证码"))
import res_rc
