# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Modify_Person.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Modify_Person(object):
    def setupUi(self, Modify_Person):
        Modify_Person.setObjectName("Modify_Person")
        Modify_Person.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Modify_Person)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(270, 220, 120, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(200, 49, 481, 451))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(60, 100, 371, 321))
        self.frame_2.setStyleSheet("font: 75 15pt \"微软雅黑\";\n"
"background-color: rgb(255, 255, 255);")
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.pushButton_P_modify = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_P_modify.setStyleSheet("QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_P_modify.setObjectName("pushButton_P_modify")
        self.verticalLayout.addWidget(self.pushButton_P_modify, 0, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(120, 40, 281, 52))
        self.label.setStyleSheet("font: 75 20pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setGeometry(QtCore.QRect(410, 0, 71, 41))
        self.frame_10.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_8.setStyleSheet("QPushButton:hover{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_8.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/24gl-minimization.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_9.setStyleSheet("QPushButton:hover{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_9.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/Close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        Modify_Person.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Modify_Person)
        self.statusbar.setObjectName("statusbar")
        Modify_Person.setStatusBar(self.statusbar)

        self.retranslateUi(Modify_Person)
        self.pushButton_8.clicked.connect(Modify_Person.showMinimized) # type: ignore
        self.pushButton_9.clicked.connect(Modify_Person.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Modify_Person)

    def retranslateUi(self, Modify_Person):
        _translate = QtCore.QCoreApplication.translate
        Modify_Person.setWindowTitle(_translate("Modify_Person", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("Modify_Person", "用户名："))
        self.lineEdit_2.setPlaceholderText(_translate("Modify_Person", "邮箱："))
        self.lineEdit_3.setPlaceholderText(_translate("Modify_Person", "个性签名："))
        self.lineEdit_4.setPlaceholderText(_translate("Modify_Person", "密码："))
        self.pushButton_P_modify.setText(_translate("Modify_Person", "确认"))
        self.label.setText(_translate("Modify_Person", "修改个人信息"))
import res_rc
